
export const GET_CONFIG = 'GET_CONFIG'
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS'
export const GET_CONFIG_FAILURE = 'GET_CONFIG_FAILURE'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const SIGNOUT = 'SIGNOUT'

export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const GET_SAVES = 'GET_SAVES'
export const GET_SAVES_SUCCESS = 'GET_SAVES_SUCCESS'
export const GET_SAVES_FAILURE = 'GET_SAVES_FAILURE'

export const READ_SAVE = 'READ_SAVE'
export const READ_SAVE_SUCCESS = 'READ_SAVE_SUCCESS'
export const READ_SAVE_FAILURE = 'READ_SAVE_FAILURE'

export const UPLOAD_PILOT = 'UPLOAD_PILOT'
export const UPLOAD_PILOT_SUCCESS = 'UPLOAD_PILOT_SUCCESS'
export const UPLOAD_PILOT_FAILURE = 'UPLOAD_PILOT_FAILURE'
